contracts/StoryProtocolGateway.sol, contracts/interfaces/IStoryProtocolGateway.sol, test/StoryProtocolGateway.t.sol, test/mocks/MockERC721.sol
Add `registerIp` which allows registering an existing NFT as an IP with optional metadata. If metadata is non-empty, a signature is required to allow SPG to set the metadata.
Test added for `registerIp`.
Closes #7
SPG will be upgraded once this PR is merged.
=> Add Function to Enable Registering IP with metadata

contracts/StoryProtocolGateway.sol, contracts/interfaces/IStoryProtocolGateway.sol, script/UpgradeSPGNFT.s.sol, test/StoryProtocolGateway.t.sol
This PR introduces the following minor updates:
- Added missing parameter comments to SPG and its interface.
- Removed a redundant assert statement from SPG tests.
- Removed the unnecessary Create3 deployer from the SPGNFT upgrade script.
=> chore: add missing comments, remove redundant assertion & create3 deployer

contracts/SPGNFT.sol, contracts/StoryProtocolGateway.sol, contracts/interfaces/ISPGNFT.sol, contracts/interfaces/IStoryProtocolGateway.sol, test/StoryProtocolGateway.t.sol
This PR merges `nftMetadata` into `struct IPMetadata` for better readability and parameter handling. The updated `IPMetadata` struct is:
```solidity
struct IPMetadata {
string ipMetadataURI;
bytes32 ipMetadataHash;
string nftMetadataURI;
bytes32 nftMetadataHash;
}
```
- Refactor SPG function parameters to use the merged `IPMetadata` struct.
- Update parameter names in SPGNFT for consistency.
- Update tests to align with the new SPG function parameters.
All existing tests pass locally.
This change affects the `IStoryProtocolGateway` interface. Make sure all function calls are updated accordingly.
=> refactor(metadata): merge `nftMetadata` into `struct IPMetadata`

MULTICALL.md, contracts/StoryProtocolGateway.sol, test/StoryProtocolGateway.t.sol
This PR integrates the `multicall` function to enable batched transaction calls for SPG functions.
- SPG now inherits OpenZeppelin's `MulticallUpgradeable` contract to leverage its `multicall` functionality.
- Added documentation for batching transactions.
- Implemented new integration tests for `multicall`.
All tests pass locally.
Closes #33
=> feat(spg): add multicall integration

script/Main.s.sol
This PR removes the duplicated `_endBroadcast` call in the deployment script which was causing deployment to fail.
All existing tests passes locally.
=> fix(deploy-script): remove duplicated `_endBroadcast` call

.gitignore, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, docs/DEPLOY_UPGRADE.md, docs/MULTICALL.md, docs/WORKFLOWS.md
This PR enhances documentation by adding:
- A root-level README
- A Code of Conduct
- Contribution Guidelines
- An Upgrade and Deployment Guide
- A list of currently supported workflows
- Updates to the Multicall guide
This PR closes #46
=> docs: add documentation

contracts/BaseWorkflow.sol, contracts/GroupingWorkflows.sol, contracts/SPGNFT.sol, contracts/StoryProtocolGateway.sol, contracts/interfaces/IGroupingWorkflows.sol, contracts/interfaces/ISPGNFT.sol, contracts/interfaces/IStoryProtocolGateway.sol, contracts/lib/Errors.sol, contracts/lib/LicensingHelper.sol, contracts/lib/MetadataHelper.sol, contracts/lib/PermissionHelper.sol, contracts/lib/SPGNFTLib.sol, package.json, script/Main.s.sol, script/UpgradeSPG.s.sol, script/UpgradeSPGNFT.s.sol, test/GroupingWorkflows.t.sol, test/SPGNFT.t.sol, test/StoryProtocolGateway.t.sol, test/mocks/MockERC20.sol, test/mocks/MockERC721.sol, test/mocks/MockEvenSplitGroupPool.sol, test/utils/TestProxyHelper.t.sol
This PR addresses the inconsistency in the licensing across several files within the repository. 
The repository is licensed under the MIT License, but certain contracts were previously licensed under BUSL-1.1. 
For consistency, all contracts have been updated to the MIT License.
This PR closes #45
=> fix(licensing): resolve inconsistent licenses in the repository

docs/DEPLOY_UPGRADE.md, script/deployment/Main.s.sol, script/deployment/MockRewardPool.s.sol, script/upgrade/UpgradeGroupingWorkflows.s.sol, script/upgrade/UpgradeSPG.s.sol, script/upgrade/UpgradeSPGNFT.s.sol, script/utils/StoryProtocolPeripheryAddressManager.sol
This PR introduces deployment and upgrade logic for the `GroupingWorkflows` contract.
**Key changes include**:
- Added deployment logic for `GroupingWorkflows` contract to the deployment script (`Main.s.sol`).
- Added a separate deployment script for the `MockRewardPool` contract.
- Created an upgrade script for `GroupingWorkflows`.
- Updated the SPGNFT deploy and upgrade scripts to include a parameter for the `GroupingWorkflows` address.
- Reorganized the `scripts` folder by adding `deployment` and `upgrade` directories, moving relevant scripts accordingly.
All existing and new deployment and upgrade scripts have been tested on the testnet, confirming that all scripts operate as expected. For details on the test results see the dropdown section below:
<details>
<summary>Test …
=> feat(deploy-upgrade): add deploy and upgrade scripts for `GroupingWorkflows`

package.json, yarn.lock
This PR updates SPG to reference the v1.2.0 release of protocol-core instead of tracking the main branch.
=> chore: update dependencies to protocol-core v1.2.0

contracts/GroupingWorkflows.sol, contracts/interfaces/IGroupingWorkflows.sol, docs/WORKFLOWS.md, test/GroupingWorkflows.t.sol
This PR introduces support for custom license templates in the `GroupingWorkflows` contract. This allows custom licenses to be attached to individual or group IPs using user-provided license templates, instead of being restricted to the PIL template.
**Key changes:**
- Updated all relevant `GroupingWorkflows` functions to accept a license template address as a parameter.
- Modified `attachLicenseTerms` calls to the `LicensingModule` to use the provided license template address.
- Updated tests and documentation to reflect these changes.
- Issue #54
This PR includes interface changes to `GroupingWorkflows`, which may require updating any contracts or systems interacting with it.
=> feat(grouping): add support for custom license templates in `GroupingWorkflows`

contracts/GroupingWorkflows.sol, contracts/lib/LicensingHelper.sol, foundry.toml, remappings.txt, script/utils/DeployHelper.sol, test/utils/BaseTest.t.sol
This PR adds a fix to ensure idempotency when attaching license terms in `GroupingWorkflows`.
- Added the `attachLicenseTerms` helper function, which attaches license terms only if they haven't been applied already. `GroupingWorkflows` now uses this helper instead of calling `LicensingModule` directly.
- Miscellaneous Fixes: Added EVM version, removed unnecessary imports, fixed state variable visibility, and applied minor style improvements.
All existing and new tests pass locally.
- Issue #24
=> fix(grouping): make license attachment idempotent

contracts/StoryProtocolGateway.sol, contracts/lib/LicensingHelper.sol
This PR replaces the existing minting fee calculation logic for a single parent with a call to `predictMintingLicenseFee` function from the licensing module. This function allows minting fee prediction without triggering any state changes.
All existing tests pass locally.
- Closes #61
=> feat(derivative): use licensing module's `predictMintingLicenseFee` for minting fee calculation

contracts/BaseWorkflow.sol, contracts/GroupingWorkflows.sol, contracts/SPGNFT.sol, contracts/StoryProtocolGateway.sol, contracts/lib/Errors.sol, test/StoryProtocolGateway.t.sol
This PR adds public minting support for SPG functions that handle minting. It replaces the `onlyCallerWithMinterRole` access control modifier with `onlyMintAuthorized`, which checks if the caller is authorized to mint—either by having the minter role in the given SPG NFT contract or if the contract has `publicMinting` enabled.
- Added `test_SPG_revert_mintAndRegisterIp_callerNotAuthorizedToMint` to verify that minting is blocked when the caller doesn't have the minter role and public minting is disabled in the collection.
- Added `test_SPG_mintAndRegisterIp_publicMint` to test that minting is allowed when public minting is enabled, even if the caller doesn't have the minter role.
- Existing tests already cover cases where the caller has the minter role, but public minting is disabled.
All …
=> feat(spg): add public minting support

test/utils/BaseTest.t.sol, yarn.lock
[PR#247](https://github.com/storyprotocol/protocol-core-v1/pull/247) in the core protocol changes the IPGraph precompile address from `0x1A` to `0x1B`, causing the periphery tests to fail. This PR updates the mock IPGraph address in the tests to `0x1B` for consistency.
All existing tests pass locally
=> fix(test): change mock IPGraph precompile address to `0x1B`

contracts/interfaces/workflows/IRoyaltyWorkflows.sol, contracts/workflows/RoyaltyWorkflows.sol, test/workflows/RoyaltyWorkflows.t.sol
This PR implements the enhancement proposed in PR #74  by removing the `currencyTokens` parameter from the methods `transferToVaultAndSnapshotAndClaimByTokenBatch` and `transferToVaultAndSnapshotAndClaimBySnapshotBatch`. The functions now internally extract the list of unique currency token addresses from the `royaltyClaimDetails` parameter. 
- Removed the `currencyTokens` parameter from the function signatures of:
- `transferToVaultAndSnapshotAndClaimByTokenBatch`
- `transferToVaultAndSnapshotAndClaimBySnapshotBatch`
- Added a private function `_getCurrencyTokenList` that extracts a unique list of currency token addresses from the `royaltyClaimDetails` array.
- Modified existing tests to accommodate the changes in function parameters.
- Added additional assertions in the …
=> feat(royalty): remove `currencyTokens` parameter and extract internally in batch claim functions

.github/workflows/foundry_ci.yml, contracts/RoyaltyWorkflows.sol, contracts/interfaces/IRoyaltyWorkflows.sol, contracts/lib/Errors.sol, package.json, test/RoyaltyWorkflows.t.sol, test/mocks/MockERC20.sol, test/utils/BaseTest.t.sol, test/utils/Users.t.sol, yarn.lock
This PR adds the changes from PRs #74 and #75 to the release branch. It introduces the `RoyaltyWorkflows` contract, which enables IP royalty token holders to claim revenue across multiple revenue tokens and snapshots in a single function call. 
Additionally, the `package.json` is updated to reference `protocol-core` version **v1.2.2**.
All existing and new tests pass locally.
=> Add `RoyaltyWorkflows` to Release Branch

script/utils/StoryProtocolCoreAddressManager.sol, test/integration/BaseIntegration.t.sol, test/integration/README.md, test/integration/workflows/DerivativeIntegration.t.sol, test/integration/workflows/GroupingIntegration.t.sol, test/integration/workflows/LicenseAttachmentIntegration.t.sol, test/integration/workflows/RegistrationIntegration.t.sol, test/integration/workflows/RoyaltyIntegration.t.sol, test/workflows/DerivativeWorkflows.t.sol, test/workflows/RoyaltyWorkflows.t.sol, yarn.lock
This PR introduces integration tests for the periphery contracts. These tests are intended to be run against a live deployment of the PoC periphery contracts, sending real transactions to the blockchain. The new integration tests include:
- `DerivativeIntegration`
- `GroupingIntegration`
- `LicenseAttachmentIntegration`
- `RegistrationIntegration`
- `RoyaltyIntegration`
- Added documentation outlining how to run these integration tests (details see `/test/integration/README.md`).
- Corrected several typos in existing code comments.
All existing tests have passed, and the newly added integration tests have been run locally to ensure everything works as expected. For detailed test output and transaction hashes, refer to: [TestOutput.md](https://github.com/user-attachments/files/17158717/Test …
=> test: add integration tests to periphery

test/integration/BaseIntegration.t.sol, test/integration/workflows/DerivativeIntegration.t.sol, test/integration/workflows/GroupingIntegration.t.sol, test/integration/workflows/LicenseAttachmentIntegration.t.sol, test/integration/workflows/RegistrationIntegration.t.sol, test/integration/workflows/RoyaltyIntegration.t.sol
This PR introduces additional log statements for each test function in the integration tests added in PR #79. Below is a comparison showing the logs before and after the changes:
```bash
== Logs ==
==================================
Running test RegistrationIntegration ...
Test RegistrationIntegration  passed!
==================================
```
```bash
== Logs ==
🏃 Running _test_RegistrationIntegration_createCollection ...
✅ _test_RegistrationIntegration_createCollection passed!
🏃 Running _test_RegistrationIntegration_createCollection ...
✅ _test_RegistrationIntegration_createCollection passed!
🏃 Running _test_RegistrationIntegration_mintAndRegisterIp ...
✅ _test_RegistrationIntegration_mintAndRegisterIp passed!
🏃 Running _test_RegistrationIntegration_registerIp ...
✅ …
```
=> chore: enhance integration test logs for better traceability

script/upgrade/UpgradeDerivativeWorkflows.s.sol, script/upgrade/UpgradeGroupingWorkflows.s.sol, script/upgrade/UpgradeLicenseAttachmentWorkflows.s.sol, script/upgrade/UpgradeRegistrationWorkflows.s.sol, script/upgrade/UpgradeRoyaltyWorkflows.s.sol, script/upgrade/UpgradeSPGNFT.s.sol, test/integration/workflows/DerivativeIntegration.t.sol, test/integration/workflows/GroupingIntegration.t.sol, test/integration/workflows/LicenseAttachmentIntegration.t.sol, test/integration/workflows/RegistrationIntegration.t.sol, test/integration/workflows/RoyaltyIntegration.t.sol
This PR fixes an issue in the upgrade script where deployment addresses were not properly handled due to missing calls to `UpgradeHelper`'s `run()` function. 
Additionally, this PR introduces minor linting adjustments to the integration tests.
=> fix(upgrade script): add missing `super.run()` in upgrade scripts

contracts/interfaces/workflows/IGroupingWorkflows.sol, contracts/workflows/GroupingWorkflows.sol, docs/WORKFLOWS.md, test/integration/workflows/GroupingIntegration.t.sol, test/workflows/GroupingWorkflows.t.sol, yarn.lock
This PR introduces a new function, `registerGroupAndAttachLicense`, to `GroupingWorkflows`. This function allows registering and attaching license terms to a group IP without needing to add group members.
This PR also updates the package to include the fix from the core protocol ([PR #259](https://github.com/storyprotocol/protocol-core-v1/pull/259)), which resolves the issue that was preventing `GroupingWorkflows` from verifying properly.
- Added both integration and unit tests for the new function.
- Verified that all existing and new tests pass.
- Closes #82
=> feat(grouping): add `registerGroupAndAttachLicense` function

contracts/interfaces/story-nft/IERC5192.sol, contracts/interfaces/story-nft/IOrgNFT.sol, contracts/interfaces/story-nft/IStoryBadgeNFT.sol, contracts/interfaces/story-nft/IStoryNFT.sol, contracts/interfaces/story-nft/IStoryNFTFactory.sol, contracts/story-nft/BaseStoryNFT.sol, contracts/story-nft/OrgNFT.sol, contracts/story-nft/StoryBadgeNFT.sol, contracts/story-nft/StoryNFTFactory.sol, script/deployment/StoryNFT.s.sol, script/utils/DeployHelper.sol, test/story-nft/OrgNFT.t.sol, test/story-nft/StoryBadgeNFT.t.sol, test/story-nft/StoryNFTFactory.t.sol, test/utils/BaseTest.t.sol, test/workflows/DerivativeWorkflows.t.sol
This PR introduces the Story NFT contracts, enabling developers to quickly bootstrap an NFT contract with built-in functionality for IP and derivative registration.
- **`OrgNFT` & `IOrgNFT`**: Represents organizations deploying Story NFTs. Each organization is assigned a unique `OrgNFT` token, which establish a one-to-one mapping between the organization and its instance of a Story NFT contract.
- **`IStoryNFTFactory` & `StoryNFTFactory`**: Serve as the entry point for registering organizations and deploying new Story NFT contracts. The factory allows easy Story NFT creation and ensures proper linkage between organizations and their NFTs.
- **`IStoryNFT` & `BaseStoryNFT`**: An interface and abstract contract defining standard functions and behaviors for all Story NFTs. Custom Story NFTs …
=> Introduce Story NFT

contracts/interfaces/workflows/ILicenseAttachmentWorkflows.sol, contracts/workflows/LicenseAttachmentWorkflows.sol, test/integration/workflows/LicenseAttachmentIntegration.t.sol, test/integration/workflows/RoyaltyIntegration.t.sol, test/story-nft/OrgNFT.t.sol, test/story-nft/StoryBadgeNFT.t.sol, test/story-nft/StoryNFTFactory.t.sol, test/utils/BaseTest.t.sol, test/workflows/LicenseAttachmentWorkflows.t.sol, test/workflows/RoyaltyWorkflows.t.sol
This PR updates the `registerPILTermsAndAttach` function in `LicenseAttachmentWorkflows` to streamline permission handling. Previously, the caller needed to manually set permission for `LicenseAttachmentWorkflows` to invoke the `attachLicenseTerms` function in the `LicensingModule`. Now, this permission is automatically set within the function, using the provided signature.
- Added a call to `setPermissionForModule`, which grants the required permission to call `attachLicenseTerms` on behalf of the IP.
- Introduced a new parameter in `registerPILTermsAndAttach` to pass the signature required for setting the permission.
- Updated existing tests to reflect these changes.
- Minor test cleanup.
All existing tests have been updated and are passing locally.
- Closes #88
=>  feat(license attachment): add permission handling in registerPILTermsAndAttach

contracts/interfaces/story-nft/IOrgNFT.sol, contracts/interfaces/story-nft/IStoryNFT.sol, contracts/story-nft/BaseStoryNFT.sol, contracts/story-nft/OrgNFT.sol, test/story-nft/OrgNFT.t.sol, test/story-nft/StoryBadgeNFT.t.sol
This PR enables two types of URI changes after deploying Story NFT:
1. **OrgNFT TokenURI Update**: Allows the owner of an OrgNFT to change its `tokenURI` after the token has been minted.
2. **Story NFT ContractURI Update**: Allows the owner of the Story NFT contract to change its `contractURI` after the contract has been deployed.
Added new test cases for setting the URIs. All new and existing tests pass locally.
- Closes #90
=> feat(story-nft): enable URI changes post deployment

contracts/SPGNFT.sol, contracts/interfaces/ISPGNFT.sol, contracts/interfaces/story-nft/IERC7572.sol, contracts/interfaces/story-nft/IStoryBadgeNFT.sol, contracts/interfaces/story-nft/IStoryNFT.sol, contracts/story-nft/BaseStoryNFT.sol, test/SPGNFT.t.sol, test/integration/BaseIntegration.t.sol, test/integration/workflows/DerivativeIntegration.t.sol, test/integration/workflows/GroupingIntegration.t.sol, test/integration/workflows/LicenseAttachmentIntegration.t.sol, test/integration/workflows/RegistrationIntegration.t.sol, test/integration/workflows/RoyaltyIntegration.t.sol, test/utils/BaseTest.t.sol, test/workflows/RegistrationWorkflows.t.sol
This PR introduces ERC-7572 contract-level metadata support to `SPGNFT` and updates the existing contract-level metadata in `IStoryNFT` and `BaseStoryNFT` to comply with the ERC-7572 standard.
- Added `IERC7572`; both `IStoryNFT` and `SPGNFT` now inherit from `IERC7572`.
- Introduced a new `_contractURI` field in `SPGNFTStorage`, along with corresponding getter (`contractURI`) and setter (`setContractURI`) functions in SPGNFT.
- `setContractURI` in `BaseStoryNFT` now emits `ContractURIUpdated` event defined in `IERC7572`
- Minor cleanups:
- Removed redundant inheritance in `ISPGNFT`.
- Updated setter functions in `SPGNFT` to be external rather than public.
- Added tests for the `setContractURI` function in `SPGNFT`.
- Added assertions for `contractURI` in `SPGNFT` initialization and …
=> feat(SPGNFT): add ERC-7572 contract-level metadata support

contracts/story-nft/StoryBadgeNFT.sol, contracts/story-nft/StoryNFTFactory.sol
This PR addresses a reentrancy vulnerability in the `mint` function of the `StoryBadgeNFT` contract. The issue arises because `_safeTransfer` invokes the `onERC721Received` hook, which could potentially re-enter the `mint` function and bypass the used signature check.
This issue is resolved by moving the `_usedSignature[signature] = true` update before the `_safeTransfer` function so that the signature is marked as used before any external calls are made.
=> fix(story-nft): resolve reentrancy vulnerability

contracts/hooks/TotalLicenseTokenLimitHook.sol, test/hooks/TotalLicenseTokenLimitHook.t.sol
This PR introduces a new Licensing Hook, `TotalLicenseTokenLimitHook`, which allows IP owners to set a limit on the total number of license tokens that can be minted from specific license terms of an IP. This feature ensures that the minting of license tokens is controlled and adheres to the predefined limits set by the IP owner.
- **Set Total License Token Limit**: IP owners can specify the maximum number of license tokens that can be minted for a given license template and terms.
- **Minting Fee Calculation**: The hook calculates the minting fee based on the license template and terms.
- **Validation**: The hook validates the total supply of license tokens before allowing new tokens to be minted, ensuring the limit is not exceeded.
- **Revert on Exceeding Limit**: If the minting request …
=> Introduce Licensing Hook for Limiting Total License Tokens

contracts/hooks/TotalLicenseTokenLimitHook.sol, test/hooks/TotalLicenseTokenLimitHook.t.sol
This PR adds checks to the `setTotalLicenseTokenLimit` function that revert if the new license token limit is lower than the current total supply. Additionally, it introduces new custom errors to replace the existing require statements.
Added a new test case to verify that the `setTotalLicenseTokenLimit` function correctly reverts when the new limit is lower than the current total supply. All existing tests pass locally.
=>  fix(licensing-hook): prevent setting license token limit below current total supply

contracts/lib/WorkflowStructs.sol, contracts/story-nft/BaseStoryNFT.sol, contracts/story-nft/OrgNFT.sol, contracts/story-nft/StoryBadgeNFT.sol, contracts/workflows/DerivativeWorkflows.sol, script/deployment/Main.s.sol, script/deployment/StoryNFT.s.sol, script/utils/DeployHelper.sol, test/hooks/TotalLicenseTokenLimitHook.t.sol, test/integration/workflows/DerivativeIntegration.t.sol, test/integration/workflows/RoyaltyIntegration.t.sol, test/workflows/DerivativeWorkflows.t.sol, test/workflows/GroupingWorkflows.t.sol, test/workflows/LicenseAttachmentWorkflows.t.sol, test/workflows/RoyaltyWorkflows.t.sol, yarn.lock
This PR updates the periphery’s dependency on the PoC core to include changes from [PR#204](https://github.com/storyprotocol/protocol-core-v1/pull/204) up to [PR#280](https://github.com/storyprotocol/protocol-core-v1/pull/280). It modifies the periphery contracts, tests, and scripts to adapt to these PoC core updates.
- Added an extra `maxMintingFee` parameter when calling `registerDerivative` and `mintLicenseTokens` in `LicensingModule`.
- Introduced a new `commercialRevShare` field to `LicensingConfig`.
- Replaced the `commercialUse` license with `commercialRemix` in derivative tests.
- Made minor changes to deployment scripts.
All existing tests pass locally.
=> fix: update periphery to align with PoC core changes

contracts/hooks/LockLicenseHook.sol, test/hooks/LockLicenseHook.t.sol, test/hooks/TotalLicenseTokenLimitHook.t.sol
This PR introduces the `LockLicenseHook` contract, which is designed to prevent any license token minting, derivative registration, and minting fee calculations. This hook can be used to effectively lock a license, preventing any further operations on it.
- Added `LockLicenseHook` contract in `contracts/hooks/LockLicenseHook.sol`
- Implemented `ILicensingHook` interface
- Added custom error `LockLicenseHook_LicenseLocked`
- Implemented `beforeMintLicenseTokens`, `beforeRegisterDerivative`, and `calculateMintingFee` functions to always revert
- Added `supportsInterface` function for ERC165 compliance
Tested integration with the `LicensingModule` to verify that the hook prevents minting and derivative registration.
1. To lock or disable a license:
- IP owners should set the license …
=> feat(hooks): add `LockLicenseHook` to locking/disabling licensing operations

contracts/interfaces/workflows/IGroupingWorkflows.sol, contracts/workflows/GroupingWorkflows.sol, script/upgrade/UpgradeGroupingWorkflows.s.sol, script/utils/DeployHelper.sol, test/workflows/DerivativeWorkflows.t.sol, test/workflows/GroupingWorkflows.t.sol
Currently, the core protocol lacks a function to manually trigger royalty vault deployment. This leads to an issue in the `collectRoyaltiesAndClaimReward` function, where a member IP may not have a royalty vault if no license token has been minted or no derivative has been registered.
This PR addresses the issue by adding a workaround in the `collectRoyaltiesAndClaimReward` function. It now checks whether the given member IP already has a royalty vault deployed, and if not, it mints a license token for that IP to trigger the royalty vault deployment.
- Added logic to check for and deploy royalty vaults for member IPs as needed
- Renamed `GroupId` to `GroupIpId` in `collectRoyaltiesAndClaimReward`
- Updated tests to reflect these changes
=> fix(grouping): deploy royalty vault for member IPs without existing vaults

CHANGELOG.md, README.md, deploy-out/deployment-1516.json, docs/WORKFLOWS.md, package.json, script/utils/BroadcastManager.s.sol, script/utils/StoryProtocolCoreAddressManager.sol, test/integration/BaseIntegration.t.sol, test/integration/workflows/DerivativeIntegration.t.sol, test/integration/workflows/GroupingIntegration.t.sol, test/workflows/DerivativeWorkflows.t.sol, yarn.lock
- Integration Test Updates:
- Modified `GroupingWorkflows` integration test to use `EvenSplitGroupPool` from the protocol core deployment info.
- Updated `BroadcastManager` to include the new chain ID.
- Adjusted `DerivativeWorkflows` integration test to use the `CommercialRemix` license, replacing the previous `CommercialUse` license.
- Updated `BaseIntegration` to include mock IPGraph precompile.
- Added changelog for version v1.2.4.
- Updated docs to incelude `collectRoyaltiesAndClaimReward` function in `GroupingWorkflows`.
- Updated contract deployment addresses.
- Bumped the package version to v1.2.4.
=> fix(integ-test): fix integration test & release v1.2.4

contracts/BaseWorkflow.sol, contracts/SPGNFT.sol, contracts/interfaces/ISPGNFT.sol, contracts/interfaces/workflows/IDerivativeWorkflows.sol, contracts/interfaces/workflows/IGroupingWorkflows.sol, contracts/interfaces/workflows/ILicenseAttachmentWorkflows.sol, contracts/interfaces/workflows/IRegistrationWorkflows.sol, contracts/lib/Errors.sol, contracts/workflows/DerivativeWorkflows.sol, contracts/workflows/GroupingWorkflows.sol, contracts/workflows/LicenseAttachmentWorkflows.sol, contracts/workflows/RegistrationWorkflows.sol, test/SPGNFT.t.sol, test/integration/workflows/DerivativeIntegration.t.sol, test/integration/workflows/GroupingIntegration.t.sol, test/integration/workflows/LicenseAttachmentIntegration.t.sol, test/integration/workflows/RegistrationIntegration.t.sol, test/integration/workflows/RoyaltyIntegration.t.sol, test/workflows/DerivativeWorkflows.t.sol, test/workflows/GroupingWorkflows.t.sol, test/workflows/LicenseAttachmentWorkflows.t.sol, test/workflows/RegistrationWorkflows.t.sol
This PR adds a new deduplication option to the `mint` and `mintByPeriphery` functions in `SPGNFT`, integrating this option into the existing workflow functions that use `SPGNFT`.
- In `SPGNFT`, the`mint` and `mintByPeriphery` functions will check if the dedup parameter is set to true and skip the minting process if the `nftMetadataHash` has already been used. Instead, the function will return the token ID of the original mint associated with that metadata hash.
- In `RegistrationWorkflows`, `DerivativeWorkflows`, `LicenseAttachmentWorkflows`, and `GroupingWorkflows`, attempting to mint with a duplicated `nftMetadataHash` while `dedup` is enabled will throw an error containing information about the IP that was first registered with the metadata hash.
- If the `dedup` flag is set to false, …
=> feat(spg-nft): add deduplication option to mint functions

contracts/interfaces/story-nft/IOrgStoryNFT.sol, contracts/interfaces/story-nft/IStoryNFT.sol, contracts/interfaces/story-nft/IStoryNFTFactory.sol, contracts/story-nft/BaseOrgStoryNFT.sol, contracts/story-nft/BaseStoryNFT.sol, contracts/story-nft/StoryBadgeNFT.sol, contracts/story-nft/StoryNFTFactory.sol, test/story-nft/StoryBadgeNFT.t.sol, test/story-nft/StoryNFTFactory.t.sol
This PR refactors `BaseStoryNFT` by extracting `OrgNFT` logic into a newly created child contract, `BaseOrgStoryNFT`, to enhance modularity and generalizability. Additionally, it introduces ERC-7201-compliant namespaced storage for both `BaseStoryNFT` and `BaseOrgStoryNFT` for future upgradability for inheriting contracts.
- Removed `orgNft`, `orgTokenId`, and `orgIpId` from `BaseStoryNFT`’s constructor and initializer.
- Introduced `BaseOrgStoryNFT` as a child contract of `BaseStoryNFT`, incorporating `orgNft`, `orgTokenId`, and `orgIpId` in its constructor and initializer, with relevant getters added.
- Implemented ERC-7201-compliant namespaced storage for both `BaseStoryNFT` and `BaseOrgStoryNFT`, including internal and external initializers.
- Updated `BaseStoryNFT` to inherit from …
=> refactor(story-nft): extract `OrgNFT` logic to `BaseOrgStoryNFT`

contracts/interfaces/story-nft/IOrgNFT.sol, contracts/interfaces/story-nft/IOrgStoryNFTFactory.sol, contracts/interfaces/story-nft/IStoryBadgeNFT.sol, contracts/story-nft/BaseOrgStoryNFT.sol, contracts/story-nft/BaseStoryNFT.sol, contracts/story-nft/OrgNFT.sol, contracts/story-nft/OrgStoryNFTFactory.sol, contracts/story-nft/StoryBadgeNFT.sol, script/upgrade/UpdateDefaultOrgStoryNFTTemplate.s.sol, script/upgrade/UpgradeOrgNFT.s.sol, script/utils/DeployHelper.sol, test/story-nft/OrgNFT.t.sol, test/story-nft/OrgStoryNFTFactory.t.sol, test/story-nft/StoryBadgeNFT.t.sol, test/utils/BaseTest.t.sol
This PR introduces the ability to set IP metadata during the minting process for `OrgNFT` and `BaseStoryNFT`. It ensures that when a new IP is registered, its metadata is provided by the user and set through `CoreMetadataModule`.
- Integrated logic for setting IP metadata into the internal `_mintAndRegisterIp` function in both `BaseStoryNFT` and `OrgNFT`.
- Added three storage variables to `StorageBadgeNFT` for storing IP metadata, which will be initialized during deployment. The same metadata will be the same across all badges in the collection.
- Updated mint functions in `OrgNFT` to accept the `IPMetadata` struct defined in `WorkflowStructs`.
- Updated `OrgStoryNFTFactory` deployment functions to accept the `IPMetadata` struct and pass it during the minting of `OrgNFTs`.
Added calls to …
=> feat(story-nft): implement IP metadata setting during mint

contracts/story-nft/CachableNFT.sol, test/story-nft/StoryBadgeNFT.t.sol
This PR fixes an issue where NFT information was not properly removed from the cache after `transferFromCache` due to incorrect usage of the `remove` method from `EnumerableMap`. Additionally, this PR introduces new getter functions to allow viewing the current state of the cache.
=> fix(cachable-nft): fix removing NFT from cache & add cache state getter

contracts/story-nft/CachableNFT.sol, test/story-nft/StoryBadgeNFT.t.sol
Implement automatic caching support that activates when the block base fee exceeds a specified threshold.
=> fix(cachable-nft): support auto cache

contracts/interfaces/workflows/IGroupingWorkflows.sol, contracts/interfaces/workflows/IRoyaltyWorkflows.sol, contracts/workflows/GroupingWorkflows.sol, contracts/workflows/RoyaltyWorkflows.sol, docs/WORKFLOWS.md, test/integration/workflows/GroupingIntegration.t.sol, test/integration/workflows/RoyaltyIntegration.t.sol, test/workflows/GroupingWorkflows.t.sol, test/workflows/RoyaltyWorkflows.t.sol, yarn.lock
This PR simplifies `RoyaltyWorkflows` and `GroupingWorkflows` to use the updated royalty vault API, introduced in [PR#291](https://github.com/storyprotocol/protocol-core-v1/pull/291/) of the core protocol, which simplifies the royalty claiming process by removing the need for snapshots.
- Removed the following functions from `RoyaltyWorkflows`:
- `transferToVaultAndSnapshotAndClaimBySnapshotBatch`
- `snapshotAndClaimBySnapshotBatch`
- `snapshotAndClaimByTokenBatch`
- Modified `transferToVaultAndSnapshotAndClaimBySnapshotBatch` in `RoyaltyWorkflows` to remove snapshot logic and renamed it to `transferToVaultAndClaimByTokenBatch`.
- Added `claimAllRevenue` in `RoyaltyWorkflows` to allow claiming all available revenue for an ancestor IP.
- Removed snapshot logic from …
=> Simplify Royalty Claims in `RoyaltyWorkflows` and `GroupingWorkflows` by Removing Snapshots

README.md, contracts/interfaces/workflows/ILicenseAttachmentWorkflows.sol, contracts/lib/LicensingHelper.sol, contracts/workflows/DerivativeWorkflows.sol, contracts/workflows/LicenseAttachmentWorkflows.sol, contracts/workflows/RoyaltyWorkflows.sol, docs/WORKFLOWS.md, test/integration/workflows/LicenseAttachmentIntegration.t.sol, test/integration/workflows/RoyaltyIntegration.t.sol, test/workflows/DerivativeWorkflows.t.sol, test/workflows/GroupingWorkflows.t.sol, test/workflows/LicenseAttachmentWorkflows.t.sol, test/workflows/RoyaltyWorkflows.t.sol
This PR introduces support for custom license templates in `LicenseAttachmentWorkflows`. It removes the needs for license term IDs prediction during signature generation by decoupling license term registration from the `registerIpAndAttachPILTerms` function.
- Removed the `registerPILTermsAndAttach` function from `LicenseAttachmentWorkflows`.  
- Renamed and refactored:  
- `registerIpAndAttachPILTerms` is now `registerIpAndAttachLicenseTerms`.  
- It now accepts a license template and an already registered license term ID, instead of registering new terms internally.  
- Added `mintAndRegisterIpAndAttachLicenseTerms` to support IP registration for an existing NFT and attaching pre-registered license terms.  
- Updated documentation to reflect these changes.
Refactored tests to align with …
=> feat(licensing): support custom license templates and decouple terms registration from attachment

.github/workflows/foundry_ci.yml, contracts/interfaces/workflows/ILicenseAttachmentWorkflows.sol, contracts/lib/LicensingHelper.sol, contracts/workflows/LicenseAttachmentWorkflows.sol, test/integration/workflows/DerivativeIntegration.t.sol, test/integration/workflows/LicenseAttachmentIntegration.t.sol, test/integration/workflows/RoyaltyIntegration.t.sol, test/workflows/DerivativeWorkflows.t.sol, test/workflows/LicenseAttachmentWorkflows.t.sol, test/workflows/RoyaltyWorkflows.t.sol
This PR introduces support for attaching multiple licenses in all `LicenseAttachmentWorkflows` functions.
- Updated `registerPILTermsAndAttach`, `mintAndRegisterIpAndAttachPILTerms`, and `registerIpAndAttachPILTerms` to accept an array of PIL terms for registration and attachment.
- Updated `LicensingHelper` to handle the registration and attachment of multiple licenses.
- Modified existing tests for `LicenseAttachmentWorkflows` to validate the attachment of 5 licenses per function call instead of one.
- Refactored tests to align with the updated functionality.
- Issue #124
=> feat(licensing): enable multi-license attachment in `LicenseAttachmentWorkflows`

contracts/interfaces/workflows/ILicenseAttachmentWorkflows.sol, contracts/workflows/LicenseAttachmentWorkflows.sol, test/workflows/LicenseAttachmentWorkflows.t.sol
This PR restores the single license attachment functions in `LicenseAttachmentWorkflows` that were modified in #125. These changes ensure backward compatibility with earlier implementations.  
Reinstated previous test cases for the reintroduced functions. All tests pass locally.
=> fix(licensing): reintroduce single license attachment functions for backward compatibility

contracts/interfaces/workflows/IGroupingWorkflows.sol, contracts/interfaces/workflows/ILicenseAttachmentWorkflows.sol, contracts/lib/LicensingHelper.sol, contracts/lib/WorkflowStructs.sol, contracts/workflows/GroupingWorkflows.sol, contracts/workflows/LicenseAttachmentWorkflows.sol, test/integration/workflows/DerivativeIntegration.t.sol, test/integration/workflows/GroupingIntegration.t.sol, test/integration/workflows/LicenseAttachmentIntegration.t.sol, test/workflows/DerivativeWorkflows.t.sol, test/workflows/GroupingWorkflows.t.sol, test/workflows/LicenseAttachmentWorkflows.t.sol
This PR introduces support for attaching multiple licenses in the `LicenseAttachmentWorkflows` and `GroupingWorkflows` contracts on the main branch.
- Updated `mintAndRegisterIpAndAttachPILTerms`, `mintAndRegisterIpAndAttachLicenseTerms`, and `registerIpAndAttachLicenseTerms` in `LicenseAttachmentWorkflows` to support arrays of PIL terms/license template addresses and license term IDs for attaching multiple licenses to a newly registered IP.
- Updated `mintAndRegisterIpAndAttachLicenseAndAddToGroup` and `registerIpAndAttachLicenseAndAddToGroup` in `GroupingWorkflows` to support arrays of license template addresses and license term IDs for attaching multiple licenses to new group member IPs.
- Updated `registerPILTermsAndAttach` in `LicensingHelper` to manage the registration and …
=> feat(licensing): enable multi-license attachment

contracts/interfaces/workflows/IGroupingWorkflows.sol, contracts/interfaces/workflows/ILicenseAttachmentWorkflows.sol, contracts/lib/LicensingHelper.sol, contracts/lib/WorkflowStructs.sol, contracts/workflows/GroupingWorkflows.sol, contracts/workflows/LicenseAttachmentWorkflows.sol, test/integration/BaseIntegration.t.sol, test/integration/workflows/DerivativeIntegration.t.sol, test/integration/workflows/GroupingIntegration.t.sol, test/integration/workflows/LicenseAttachmentIntegration.t.sol, test/integration/workflows/RoyaltyIntegration.t.sol, test/utils/BaseTest.t.sol, test/workflows/DerivativeWorkflows.t.sol, test/workflows/GroupingWorkflows.t.sol, test/workflows/LicenseAttachmentWorkflows.t.sol, test/workflows/RoyaltyWorkflows.t.sol
This PR introduces support for multi-license attachment and the ability to set licensing configurations during IP registration. It also updates the periphery contracts to align with recent protocol core API changes. Furthermore, signature requirements in `LicenseAttachmentWorkflows` have been streamlined using `setBatchPermissions`.
- Added `PILTermsData` and `LicenseData` in `WorkflowStructs` to consolidate licensing-related parameters.
- Modified `LicenseAttachmentWorkflows` functions to support an array of `PILTermsData` for registering and attaching multiple PIL terms and licensing configurations to IPs.
- Updated `GroupingWorkflows` functions to accept an array of `LicenseData` for attaching multiple licenses (license template, license terms ID, and licensing config) to IPs.
- …
=> feat(licensing): enable multi-license attachment and licensing config during IP registration

contracts/SPGNFT.sol, contracts/interfaces/workflows/IRoyaltyTokenDistributionWorkflows.sol, contracts/lib/Errors.sol, contracts/lib/LicensingHelper.sol, contracts/lib/WorkflowStructs.sol, contracts/workflows/DerivativeWorkflows.sol, contracts/workflows/RoyaltyTokenDistributionWorkflows.sol, script/upgrade/UpgradeSPGNFT.s.sol, script/utils/DeployHelper.sol, script/utils/StoryProtocolCoreAddressManager.sol, script/utils/StoryProtocolPeripheryAddressManager.sol, script/utils/upgrades/UpgradeHelper.s.sol, test/SPGNFT.t.sol, test/utils/BaseTest.t.sol, test/workflows/LicenseAttachmentWorkflows.t.sol, test/workflows/RoyaltyTokenDistributionWorkflows.t.sol
This PR introduces `RoyaltyTokenDistributionWorkflows` to the main branch, along with several enhancements to its functionality. These changes build upon the version introduced in `release-v1.2.4` in #126 for periphery v1.2.  
- Eliminated the need to pay extra license minting fees during IP royalty vault deployment. Achieved this by attaching a temporary commercial-use license with a minting fee of 0 and disabling the license immediately after deployment.  
- Leveraged `setBatchPermission` to reduce signature requirements. All functions now require at most one signature from the user.  
- Integrated the latest protocol core API.  
- Added the ability to set licensing configurations during license attachment.  
Modified the existing tests to align with the changes, and all tests pass …
=> feat: introduce `RoyaltyTokenDistributionWorkflows` to `main` for royalty token distribution upon IP registration  

contracts/interfaces/workflows/IRoyaltyWorkflows.sol, contracts/workflows/RoyaltyWorkflows.sol, docs/WORKFLOWS.md, test/integration/workflows/GroupingIntegration.t.sol, test/integration/workflows/RoyaltyIntegration.t.sol, test/workflows/GroupingWorkflows.t.sol, test/workflows/RoyaltyWorkflows.t.sol, yarn.lock
This PR updates the `RoyaltyWorkflows` contract to align with the changes introduced in [core protocol PR#324](https://github.com/storyprotocol/protocol-core-v1/pull/324). The update simplifies the `transferToVault` function by removing the `amount` parameter, and makes sure that the maximum available amount is always transferred to the IP royalty vault.
- `transferToVaultAndClaimByTokenBatch` has been removed, as specifying an amount to claim is no longer supported under the updated policy.
-  Adjusted existing tests to accommodate the updated functionality and ensure coverage for the revised workflow.
- Refreshed relevant packages to support the new changes.
=> fix(royalty): update `RoyaltyWorkflows` to reflect core protocol royalty policy changes

script/utils/DeployHelper.sol, yarn.lock
This PR updates the deployment helper to accommodate changes from the core protocol updates:  
- [PR#340](https://github.com/storyprotocol/protocol-core-v1/pull/340)  
- [PR#344](https://github.com/storyprotocol/protocol-core-v1/pull/344)  
The changes introduce additional constructor parameters for the `LicenseToken` and `GroupingModule` contracts.
=> chore: update deploy helper to align with core protocol updates

script/utils/DeployHelper.sol
This PR updates the visibility of private helper functions in `DeployHelper` to `internal`.  
This change enables these functions to be reused in derived contracts.
=> fix(deploy-helper): change helper functions' visibility to internal for reuse

contracts/interfaces/workflows/IRoyaltyTokenDistributionWorkflows.sol, contracts/lib/LicensingHelper.sol, contracts/workflows/RoyaltyTokenDistributionWorkflows.sol, test/workflows/RoyaltyTokenDistributionWorkflows.t.sol
This PR adds support for attaching multiple licenses for function `mintAndRegisterIpAndAttachPILTermsAndDistributeRoyaltyTokens` and `registerIpAndAttachPILTermsAndDeployRoyaltyVault` in `RoyaltyTokenDistributionWorkflows`
=> feat: support for multi license attachment in RT distribution flow

contracts/modules/tokenizer/OwnerableERC20.sol, contracts/modules/tokenizer/TokenizerModule.sol
**Description:**
This PR introduces the `TokenizerModule` to the project. The `TokenizerModule` is designed to handle the tokenization and fractionalization of IP assets (IPA). It includes functionalities for whitelisting ERC20 token templates and tokenizing IP assets. The module integrates with the protocol-wide dispute module to ensure proper handling of disputes.
**Key Changes:**
- Added `TokenizerModule` contract.
- Integrated with the `AccessControlled` and `BaseModule` for access control and base functionalities.
**Interfaces:**
- `whitelistTokenTemplate(address tokenTemplate, bool allowed)`: Allows whitelisting or blacklisting of ERC20 token templates.
- `tokenize(address ipId, address tokenTemplate, bytes initData)`: Handles the tokenization of IP assets using the specified token …
=> Introduce Tokenizer Module

contracts/lib/Errors.sol, contracts/workflows/GroupingWorkflows.sol, contracts/workflows/LicenseAttachmentWorkflows.sol, test/workflows/GroupingWorkflows.t.sol, test/workflows/LicenseAttachmentWorkflows.t.sol
This PR introduces checks to ensure functions with multi-license attachment features properly handle empty license data arrays. The affected functions will now revert if the provided license data array is empty.
The updated functions include:  
- `mintAndRegisterIpAndAttachLicenseAndAddToGroup`  
- `registerIpAndAttachLicenseAndAddToGroup`  
- `registerPILTermsAndAttach`  
- `mintAndRegisterIpAndAttachPILTerms`  
- `registerIpAndAttachPILTerms`
New test cases have been added to confirm that each of the affected functions reverts when an empty license data array is passed.
=> fix(licensing): ensure empty license data arrays are rejected

contracts/interfaces/workflows/IDerivativeWorkflows.sol, contracts/lib/LicensingHelper.sol, contracts/lib/WorkflowStructs.sol, contracts/workflows/DerivativeWorkflows.sol, test/integration/workflows/DerivativeIntegration.t.sol, test/workflows/DerivativeWorkflows.t.sol
This PR reintroduces compatibility with protocol periphery v1.2 in `DerivativeWorkflows`. The v1.2 interface has been restored, with updated function implementations to ensure compatibility with protocol core v1.3.  
Restored and updated the test cases for the v1.2 interface. All tests passes locally.
- Addresses part of #131.
Downstream integrations should now use the added `MakeDerivativeDEPR` struct (for v1.2 compatibility) in `WorkflowStructs` instead of the `MakeDerivative` struct (specific to v1.3). No additional changes are required.
=> feat(deriv): restore v1.2 compatibility to `DerivativeWorkflows`

contracts/interfaces/workflows/IGroupingWorkflows.sol, contracts/workflows/GroupingWorkflows.sol, test/integration/workflows/GroupingIntegration.t.sol, test/workflows/GroupingWorkflows.t.sol
This PR reintroduces compatibility with protocol periphery v1.2 in `GroupingWorkflows`. The v1.2 interface has been restored, with updated function implementations to ensure compatibility with protocol core v1.3.  
Restored and updated the test cases for the v1.2 interface. All tests passes locally.
- Addresses part of #131.
- Downstream integrations must update the signature passed to `registerIpAndAttachLicenseAndAddToGroup` to grant `GroupingWorkflows` permission to call the following three functions on the IP's behalf:
1. `setAll` from `CoreMetadataModule` (existing requirement in v1.2).
2. `attachLicenseTerms` from `LicensingModule` (existing requirement in v1.2).
3. `setLicensingConfig` from `LicensingModule` (new requirement).
- No additional changes are required.
=> feat(deriv): restore v1.2 compatibility to `GroupingWorkflows`

contracts/interfaces/story-nft/IERC5192.sol, contracts/interfaces/story-nft/IOrgNFT.sol, contracts/story-nft/OrgNFT.sol
This PR corrects typos in the Organization NFT contract files to improve documentation clarity and adherence to grammatical standards. Changes include replacing "a" with "an" before words beginning with vowel sounds, such as "organization" and "IP."
- `IERC5192.sol`
- Corrected grammatical error in the description of the `Unlocked` event.
- `IOrgNFT.sol`
- Updated comments and event descriptions to replace "a" with "an" where applicable.
- `OrgNFT.sol`
- Fixed typos in comments and function descriptions to ensure clarity and correctness.
=> Fix Typos in Organization NFT Contracts

contracts/interfaces/workflows/ILicenseAttachmentWorkflows.sol, contracts/workflows/LicenseAttachmentWorkflows.sol, test/workflows/LicenseAttachmentWorkflows.t.sol
This PR reintroduces compatibility with protocol periphery v1.2 in `LicenseAttachmentWorkflows`. The v1.2 interface has been restored, with updated function implementations to ensure compatibility with protocol core v1.3.  
Restored and updated the test cases for the v1.2 interface. All tests passes locally.
- Addresses part of #131.
- No additional changes are required from downstream integrations
=> feat(licensing): restore v1.2 compatibility to `LicenseAttachmentWorkflows`

contracts/interfaces/workflows/IRegistrationWorkflows.sol, contracts/workflows/RegistrationWorkflows.sol, test/integration/workflows/GroupingIntegration.t.sol, test/integration/workflows/RegistrationIntegration.t.sol, test/workflows/GroupingWorkflows.t.sol, test/workflows/RegistrationWorkflows.t.sol
This PR reintroduces compatibility with protocol periphery v1.2 in `RegistrationWorkflows`. The v1.2 interface has been restored, with updated function implementations to ensure compatibility with protocol core v1.3.  
Restored and updated the test cases for the v1.2 interface. All tests passes locally.
- Addresses part of #131.
- No additional changes are required from downstream integrations
=> feat(registration): restore v1.2 compatibility to `RegistrationWorkflows` 

contracts/interfaces/workflows/IDerivativeWorkflows.sol, contracts/interfaces/workflows/IRoyaltyTokenDistributionWorkflows.sol, contracts/workflows/DerivativeWorkflows.sol, test/integration/BaseIntegration.t.sol, test/integration/workflows/DerivativeIntegration.t.sol, test/integration/workflows/RoyaltyIntegration.t.sol, test/utils/BaseTest.t.sol, test/workflows/DerivativeWorkflows.t.sol, test/workflows/RoyaltyTokenDistributionWorkflows.t.sol, test/workflows/RoyaltyWorkflows.t.sol
This PR refactors the `registerIpAndMakeDerivative` and `registerIpAndMakeDerivativeWithLicenseTokens` functions in `DerivativeWorkflows` to leverage `setBatchPermissions` instead of setting permissions one at a time. With this change, both functions now require only a single signature to grant `DerivativeWorkflows` the necessary permissions to interact with the core protocol on behalf of the IP owner. This enhancement reduces overhead and simplifies the authorization process.
- Updated tests to reflect the use of `setBatchPermissions`.  
- all tests pass locally
- Closes #31.
=> feat(deriv): use batch permissions for derivative registration

contracts/interfaces/workflows/IRoyaltyTokenDistributionWorkflows.sol, contracts/lib/Errors.sol, contracts/lib/LicensingHelper.sol, contracts/workflows/LicenseAttachmentWorkflows.sol, contracts/workflows/RoyaltyTokenDistributionWorkflows.sol, test/workflows/RoyaltyTokenDistributionWorkflows.t.sol
This PR adds support for attaching multiple licenses for function `mintAndRegisterIpAndAttachPILTermsAndDistributeRoyaltyTokens` and `registerIpAndAttachPILTermsAndDeployRoyaltyVault` in `RoyaltyTokenDistributionWorkflows`
Existing tests are modified to verified the attachment of multiple licenses.
- Closes #138
=> feat: support for multi-license attachment in RT distribution flow 

test/hooks/TotalLicenseTokenLimitHook.t.sol, yarn.lock
This PR aligns the `TotalLicenseTokenLimitHookTest` with the protocol updates introduced in [Core Protocol PR#366](https://github.com/storyprotocol/protocol-core-v1/pull/366). The update modifies how license tokens are handled: tokens associated with default license terms no longer contribute to the licensor IP's total license token count.
To accommodate this change, the test now uses a commercial use license instead, making sure the `TotalLicenseTokenLimitHook` functions as intended under the updated logic.
=> fix(licensing hook): update tests to reflect protocol update for license token counting

.github/workflows/foundry_ci.yml, contracts/workflows/DerivativeWorkflows.sol, contracts/workflows/GroupingWorkflows.sol, contracts/workflows/LicenseAttachmentWorkflows.sol, contracts/workflows/RoyaltyTokenDistributionWorkflows.sol, script/utils/DeployHelper.sol, test/utils/BaseTest.t.sol, yarn.lock
This PR removes the unused `nftContractBeacon` storage variable and its associated functions from the following workflow contracts:  
- `DerivativeWorkflows`  
- `GroupingWorkflows`  
- `LicenseAttachmentWorkflows`  
- `RoyaltyTokenDistributionWorkflows`
=> chore(workflows): clean up unused storage variables and functions

contracts/SPGNFT.sol, contracts/interfaces/ISPGNFT.sol, contracts/interfaces/workflows/IDerivativeWorkflows.sol, contracts/workflows/DerivativeWorkflows.sol
This PR addresses misleading comments in function parameter documentation. Previously, some non-optional parameters were incorrectly labeled as optional in the comments.
=> fix: correct inaccurate comments marking non-optional parameters as optional

contracts/story-nft/OrgStoryNFTFactory.sol
This PR refactors the OrgStoryNFTFactory.sol contract to reduce code redundancy and improve code readability and maintainability.
1. Extracted Common Functions:
Extracted repeated logic from `deployOrgStoryNft` and `deployOrgStoryNftByAdmin` into two new private functions:
`_validateSignature`: Handles signature validation.
`_deployOrgStoryNft`: Executes the actual NFT deployment logic.
2. Code Optimization:
Reduced duplicate code, enhancing readability and maintainability.
Ensured all signature validation and NFT deployment logic is centralized, minimizing potential errors and inconsistencies.
All unit tests passed
=> Refactor OrgStoryNFTFactory Contract to Reduce Code Redundancy

contracts/interfaces/workflows/IDerivativeWorkflows.sol, contracts/interfaces/workflows/IGroupingWorkflows.sol, contracts/interfaces/workflows/ILicenseAttachmentWorkflows.sol, contracts/interfaces/workflows/IRegistrationWorkflows.sol, contracts/interfaces/workflows/IRoyaltyTokenDistributionWorkflows.sol, contracts/workflows/DerivativeWorkflows.sol, contracts/workflows/GroupingWorkflows.sol, contracts/workflows/LicenseAttachmentWorkflows.sol, contracts/workflows/RegistrationWorkflows.sol, contracts/workflows/RoyaltyTokenDistributionWorkflows.sol, test/workflows/DerivativeWorkflows.t.sol, test/workflows/GroupingWorkflows.t.sol, test/workflows/LicenseAttachmentWorkflows.t.sol, test/workflows/RegistrationWorkflows.t.sol, test/workflows/RoyaltyTokenDistributionWorkflows.t.sol
This PR resolves issues encountered during downstream integration with Ethereum libraries that do not fully support Solidity's function overloading. These issues caused errors when dispatching function calls on-chain. To address this, the deprecated overloaded functions have been renamed to make sure all functions have unique names.
=> fix(backwards-compatibility): rename functions to avoid overloading conflicts

contracts/lib/Errors.sol, contracts/lib/MetadataHelper.sol, contracts/lib/PermissionHelper.sol, contracts/workflows/DerivativeWorkflows.sol, contracts/workflows/GroupingWorkflows.sol, contracts/workflows/LicenseAttachmentWorkflows.sol, contracts/workflows/RoyaltyTokenDistributionWorkflows.sol, test/integration/BaseIntegration.t.sol, test/utils/BaseTest.t.sol, yarn.lock
This PR updates the permission system to use transient permissions (introduced in core protocol [PR #393](https://github.com/storyprotocol/protocol-core-v1/pull/393)) instead of permanent permissions across the workflow contracts. This change affects multiple contracts and their interactions with the `AccessController`. 
- Renamed permission-related functions to include "transient" in their names:
- `setPermission` → `setTransientPermission`
- `setBatchPermissions` → `setBatchTransientPermissions`
- `setPermissionForModule` → `setTransientPermissionForModule`
- `setBatchPermissionForModules` → `setBatchTransientPermissionForModules`
- Updated protocol-core dependency to latest version
This change improves security by making permissions temporary rather than permanent, reducing the risk of …
=> feat: replace permanent permission with transient permission

test/integration/BaseIntegration.t.sol, test/integration/workflows/LicenseAttachmentIntegration.t.sol
Fixed an issue in the license attachment integration test where an incorrect permission helper function was being used, leading to invalid signatures in the test case.
- Added new helper function `_getMetadataAndDefaultTermsPermissionList` in `BaseIntegration.t.sol` to correctly generate permissions for metadata and default license terms
- Updated `LicenseAttachmentIntegration.t.sol` to use the correct helper function instead of the invalid `_getMetadataAndAttachTermsAndConfigPermissionList`
- Renamed variables to better reflect their purpose (e.g., `sigMetadataAndAttachAndConfig` → `sigMetadataAndDefaultTerms`)
=> fix: license attachment integration tests

contracts/lib/LicensingHelper.sol, contracts/lib/PermissionHelper.sol
This PR adds array length validation checks in the following functions:  
- `setBatchPermissionForModules` in `PermissionHelper`  
- `aggregateMintFees`  
- `LicensingHelper`
=> fix: add array length matching check in internal library functions

contracts/story-nft/CachableNFT.sol
This PR locks `CachableNFT`'s pragma version to 0.8.26 and updates the license to MIT
=> fix: lock pragma version in `CachableNFT`

contracts/interfaces/story-nft/IStoryBadgeNFT.sol, contracts/story-nft/OrgStoryNFTFactory.sol, contracts/story-nft/StoryBadgeNFT.sol, test/story-nft/OrgStoryNFTFactory.t.sol, test/story-nft/StoryBadgeNFT.t.sol
This PR enhances security in the `StoryBadgeNFT` and `OrgStoryNFTFactory` contracts by adding additional validation checks to prevent duplicate minting scenarios. 
For `StoryBadgeNFT`, we now verify that a recipient can only hold one badge NFT by checking their balance before minting, regardless of signature changes. Similarly for `OrgStoryNFTFactory`, we validate that an organization NFT recipient doesn't already have an NFT before deployment. 
These changes are accompanied by new error types (`StoryBadgeNFT__RecipientAlreadyHasBadge`) and test cases to verify the updated behavior.
=> fix(story-nft): enforce max balanceOf() of 1 for each address

contracts/SPGNFT.sol, contracts/interfaces/ISPGNFT.sol, contracts/lib/Errors.sol, test/SPGNFT.t.sol
This PR adds functionality to allow NFT token owners to update their token URIs. The new `setTokenURI` function enables token owners to modify the metadata URI of their tokens while maintaining proper access control.
- Added `setTokenURI` function to `SPGNFT` contract that allows token owners to update their token URIs
- Added corresponding interface function to `ISPGNFT`
- Added new `SPGNFT__CallerNotOwner` error for unauthorized access attempts
- Added test cases to verify:
- Successful token URI updates by token owners
- Rejection of unauthorized attempts to update token URIs
- Added `test_SPGNFT_setTokenURI()` to verify successful token URI updates
- Added `test_SPGNFT_setTokenURI_revert_callerNotOwner()` to verify access control
- All tests pass successfully
- Closes #188
=> feat(SPGNFT): add `setTokenURI` function to `SPGNFT` Contract

package.json, remappings.txt, script/deployment/StoryNFT.s.sol, script/utils/StoryProtocolPeripheryAddressManager.sol, script/utils/upgrades/UpgradeHelper.s.sol, test/integration/BaseIntegration.t.sol, test/integration/workflows/DerivativeIntegration.t.sol, test/integration/workflows/GroupingIntegration.t.sol, test/integration/workflows/LicenseAttachmentIntegration.t.sol, test/integration/workflows/RegistrationIntegration.t.sol, test/integration/workflows/RoyaltyIntegration.t.sol, test/integration/workflows/RoyaltyTokenDistributionIntegration.t.sol, yarn.lock
This PR integrates the Wrapped IP token (WIP) into our testing and deployment infrastructure, replacing the previous mock ERC20 (SUSD) token. It also removes the unused Story NFT deployment addresses from `StoryProtocolPeripheryAddressManager`
- Added WIP token dependency from piplabs/wip repository
- Updated remappings to include WIP and Solady token paths
- Updated CREATE3_DEPLOYER address in Story NFT deployment scripts
- Migrated from SUSD to WIP token in all integration tests
- Simplified address management by moving unused Story NFT addresses
- Updated token amounts and fee handling to work with wrapped token pattern
All integration tests have been updated to use the WIP token instead of SUSD. The token interaction pattern has changed from direct minting to deposit-and-wrap:
- …
=> test(integration): replace mock ERC20 with Wrapped IP token (WIP) 

contracts/workflows/LicenseAttachmentWorkflows.sol
This PR enhances the documentation for several functions in the `LicenseAttachmentWorkflows` contract to clearly that they support optional licensing configuration in addition to attaching license terms.
- Clarified that `registerPILTermsAndAttach`, `mintAndRegisterIpAndAttachPILTerms`, and `registerIpAndAttachPILTerms` can all optionally set licensing configurations
- Added explanations about how licensing configurations are applied (only when `isSet` is true)
These documentation improvements help developers better understand the capabilities of the workflow functions, particularly that licensing configuration can be set in the same transaction as license term attachment.
No functional changes were made, only documentation updates.
=> docs: improve documentation for setting licensing configuration

contracts/interfaces/modules/tokenizer/ITokenizerModule.sol, contracts/lib/Errors.sol, contracts/modules/tokenizer/TokenizerModule.sol, script/utils/DeployHelper.sol, test/modules/tokenizer/TokenizerModule.t.sol
This PR adds the ability to upgrade whitelisted token template implementations in the `TokenizerModule`. The enhancement enables controlled upgrades of token implementations while maintaining system security through proper access controls.
- Added `upgradeWhitelistedTokenTemplate` function to the `TokenizerModule` and its interface
- Updated the Errors library with a new error for zero token implementation validation
- Transferred ownership of the `ownableERC20Beacon` to the `TokenizerModule`
- Added tests to verify upgrade functionality works correctly
- Function is restricted to be called only by the upgrader admin through the `restricted` modifier
- Multiple validation checks ensure that:
- Token template address is not zero
- New implementation address is not zero 
- Token template is …
=> feat: enable token template upgrades through `TokenizerModule`

contracts/interfaces/workflows/IRegistrationWorkflows.sol, contracts/workflows/RegistrationWorkflows.sol
This PR adds `setNftContractBeacon` and `upgradeCollections` to `IRegistrationWorkflows` interface to improve visibility.
- Added missing interface declarations for `setNftContractBeacon` and `upgradeCollections` functions in `IRegistrationWorkflows.sol`
- Improved function documentation to clearly indicate restricted access requirements
- Changed visibility of `upgradeCollections` function from `public` to `external` for consistency interface usage
- Updated function documentation for `setNftContractBeacon` and `upgradeCollections` to use `@notice` tags instead of `@dev` for better NatSpec documentation
- Improved documentation by using standardized phrasing for restricted access notes
This PR is part of the solution to address [issue …
=> chore: add upgrade collection functions' declaration to `IRegistrationWorkflows` interface

script/utils/DeployHelper.sol, script/utils/StoryProtocolPeripheryAddressManager.sol
This PR adds the necessary permissions to the ModuleRegistry contract to properly handle Licensing Hook upgrades. It grants the UPGRADER_ROLE the ability to call both `removeModule` and `registerModule` functions on the ModuleRegistry, which are required operations when upgrading Licensing Hooks.
=> fix(upgrade): add upgrade permissions for Licensing Hooks

contracts/workflows/RoyaltyTokenDistributionWorkflows.sol, test/workflows/RoyaltyTokenDistributionWorkflows.t.sol
This PR addresses an issue in `RoyaltyTokenDistributionWorkflows` where the deployment of a royalty vault could revert. Previously, the internal license token required for vault deployment was minted directly to `msg.sender`. This caused failures when `msg.sender` was a contract that did not implement the `onERC721Received` hook (e.g., when called via Multicall3).
The fix modifies the `_deployRoyaltyVault` function to accept an additional `licenseTokenReceiver` parameter. The workflows now pass the appropriate recipient (the IP owner) to this function, ensuring the license token is sent to an address capable of receiving it, resolving the revert condition and improving integration possibilities. Tests have been updated to verify the license token is minted to the correct owner.
- Closes …
=> fix(royalty token dist workflows): use correct recipient for license token

test/integration/workflows/GroupingIntegration.t.sol, test/integration/workflows/RegistrationIntegration.t.sol, test/utils/TestHelper.t.sol, test/workflows/DerivativeWorkflows.t.sol, test/workflows/GroupingWorkflows.t.sol, test/workflows/RegistrationWorkflows.t.sol
This PR introduces several enhancements to the integration tests, focusing on multicall functionality and IP Account state verification.
-   **Multicall Tests:** Added new integration tests in `GroupingIntegration.t.sol` to cover the multicall scenarios for:
-   `mintAndRegisterIpAndAttachLicenseAndAddToGroup`
-   `registerIpAndAttachLicenseAndAddToGroup`
-   **IP Account State Prediction:**
-   Implemented helper functions `_predictNextState` and `_predictStateSequence` in `TestHelper.t.sol`. These functions allow predicting the final state of an IP Account after one or more permissioned function calls, based on the logic in `IIPAccount.updateStateForValidSigner`.
-   Integrated state prediction assertions into existing grouping and registration integration tests …
=> fix(test): add multicall tests and IP account state prediction

.github/workflows/publish-package.yaml, package.json
The previous PR #214 introduced the forge command `forge build && forge test`, but the workflow did not include Foundry. This PR addresses that by installing Foundry as part of the workflow setup.
=> NPM Package Workflow Fix - Adds Foundry

contracts/hooks/TotalLicenseTokenLimitHook.sol, test/hooks/TotalLicenseTokenLimitHook.t.sol
This change corrects the `TotalLicenseTokenLimitHook` to enforce per-IP total license token limits.
*    Replaced `totalLicenseTokenLimit` (keyed by `licensorIpId`, `licenseTemplate`, `licenseTermsId`) with `ipIdToTotalLicenseTokenLimit` (keyed by `licensorIpId`), reflecting core protocol query limitations.
*  `SetTotalLicenseTokenLimit` event no longer includes `licenseTemplate` and `licenseTermsId` parameters.
*   Modified Function Signatures:
*   `setTotalLicenseTokenLimit(address licensorIpId, uint256 limit)`
*   `getTotalLicenseTokenLimit(address licensorIpId)`
*   Internal functions (`_checkTotalTokenLimit`) and hook callbacks (`postMintHook`, `postRegisterDerivativeHook`) updated accordingly.
*   Backward Compatibility:
*   Retained deprecated versions of …
=> fix(hooks): set `TotalLicenseTokenLimitHook` to per-IP limit

contracts/workflows/GroupingWorkflows.sol, contracts/workflows/RoyaltyTokenDistributionWorkflows.sol, test/workflows/RoyaltyTokenDistributionWorkflows.t.sol
This PR refactors the `GroupingWorkflows` and `RoyaltyTokenDistributionWorkflows` to align with the new decoupled royalty vault deployment process introduced in [storyprotocol/protocol-core-v1#435](https://github.com/storyprotocol/protocol-core-v1/pull/435).
By leveraging the `deployVault` function now available in the core protocol, periphery contracts no longer need to trigger royalty vault deployment through license token minting. This change significantly improves the user experience (UX) by simplifying workflows and avoids the need to attach additional licenses solely for the purpose of royalty vault deployment.
*   **Refactored `RoyaltyTokenDistributionWorkflows`:**
*   The workflow has been updated to utilize the core `deployVault` function for deploying royalty vaults.
* …
=> fix(rt-dist,grouping): use decoupled royalty vault deployment

contracts/SPGNFT.sol, test/SPGNFT.t.sol
This PR enhances the `SPGNFT` contract to emit the `ContractURIUpdated` event during its `initialize` function.
A new internal helper function `_setContractURI` has been introduced. This function is now responsible for setting the contract URI and handles the emission of the `ContractURIUpdated` event. The event is only emitted if the provided contract URI is different from the one currently stored.
- **`contracts/SPGNFT.sol`**:
- The `initialize` function now calls the new `_setContractURI` internal function to set the `contractURI` and handle event emission.
- Added the `_setContractURI(string memory contractURI)` internal function. This function checks if the new `contractURI` differs from the existing one (by comparing their `keccak256` hashes) before updating the storage variable and …
=> feat(spgnft): emit `ContractURIUpdated` event during initialization

contracts/hooks/TotalLicenseTokenLimitHook.sol, script/utils/DeployHelper.sol, test/hooks/TotalLicenseTokenLimitHook.t.sol
This PR modifies the `TotalLicenseTokenLimitHook` to enforce license token limits on a more granular basis: per IP Asset, per license terms.
*   **Hook Logic**:
*   The `setTotalLicenseTokenLimit` and `getTotalLicenseTokenLimit` functions in `TotalLicenseTokenLimitHook.sol` now accept `licenseTemplate` (address) and `licenseTermsId` (uint256) as parameters. This allows setting distinct limits for different license configurations associated with the same IP.
*   **Testing:**
*   Existing tests in `test/hooks/TotalLicenseTokenLimitHook.t.sol` have been updated to align with the new function signatures of the hook.
*   A new test, `test_TotalLicenseTokenLimitHook_PerIpPerLicenseLimit`, has been added to specifically verify the behavior of limits across different IPs and different license …
=> fix(hooks): enforce per-IP, per-license limits in `TotalLicenseTokenLimitHook`

.github/workflows/test-integration.yml, script/utils/StoryProtocolPeripheryAddressManager.sol, test/hooks/TotalLicenseTokenLimitHook.t.sol, test/integration/BaseIntegration.t.sol, test/integration/workflows/DerivativeIntegration.t.sol, test/integration/workflows/GroupingIntegration.t.sol, test/integration/workflows/LicenseAttachmentIntegration.t.sol, test/integration/workflows/RegistrationIntegration.t.sol, test/integration/workflows/SpgNftIntegration.t.sol
1. Updated integration tests for v1.3.3 changes ([221](https://github.com/storyprotocol/protocol-periphery-v1/pull/221), [222](https://github.com/storyprotocol/protocol-periphery-v1/pull/222)):
- Added new test in LicenseAttachmentIntegration for TotalLicenseTokenLimitHook
- Added new test SpgNftIntegration for contractURI
2. Updated integration test workflow.
3. Reduce multicall number to avoid gas fee issue - `server returned an error response: error code -32000: tx fee (4.03 ether) exceeds the configured cap (1.00 ether)`:
Original multicall number is 10: https://github.com/jia57b/protocol-periphery-v1/actions/runs/15725549668
Reducing the number of multiple calls to 2: https://github.com/jia57b/protocol-periphery-v1/actions/runs/15728009952
Run integration tests and passed: …
=> Update integration tests for release 1.3.3

test/utils/TestHelper.t.sol, test/workflows/RegistrationWorkflows.t.sol, test/workflows/RoyaltyTokenDistributionWorkflows.t.sol
This PR adds tests to the registration and royalty token distribution workflow test files. The added tests ensure that the workflow functions taking a signature as a parameter can only be called by the signer.
This PR also includes a fix in the natspec doc of the test helper `_getMetadataAndDerivativeRegistrationPermissionList` function.
test/workflows/RegistrationWorkflows.t.sol: `test_RegistrationWorkflows_revert_registerIp_callerNotSigner`
test/workflows/RoyaltyTokenDistributionWorkflows.t.sol: `test_RoyaltyTokenDistributionWorkflows_revert_CallerNotSigner_registerIpAndAttachPILTermsAndDeployRoyaltyVault`, `test_RoyaltyTokenDistributionWorkflows_revert_CallerNotSigner_registerIpAndMakeDerivativeAndDeployRoyaltyVault`, `test_RoyaltyTokenDistributionWorkflows_revert_CallerNotSigner_distri …
=> Tests registration and royalty tokens distribution workflows

test/modules/tokenizer/TokenizerModule.t.sol
This PR adds a new test function to improve test coverage for the tokenizer module, ensuring its correct behavior during tokenization.
test_TokenizerModule_revert_tokenize_TokenTemplateNotWhitelisted()
Purpose: Validates that the tokenize() function reverts when given a license template that is not whitelisted.
Before:
After:
=> fix(test): add test case to tokenizer module tests

test/SPGNFT.t.sol
This PR adds three new test functions to improve test coverage and validation for the SPGNFT contract, focusing on access control and minting permissions.
1. test_SPGNFT_mint_revert_MintingDenied()
Purpose: Validates that minting is properly denied when a user without minter role attempts to mint from a collection with public minting disabled. 
2. test_SPGNFT_setMintOpen()
Purpose: Validates the setMintOpen() function and its access control. Tests both successful state changes and access control violations.
3. test_SPGNFT_setPublicMinting()
Purpose: Validates the setPublicMinting() function and its access control. Tests both successful state changes and access control violations.
Before:
After:
=> fix(test): add missing tests for SPGNFT

test/hooks/TotalLicenseTokenLimitHook.t.sol, test/workflows/DerivativeWorkflows.t.sol
This PR adds a new test function to improve test coverage for the totalLicenseTokenLimit hook, ensuring its correct behavior during derivative registration.
It also includes a couple of linter styling changes
test_TotalLicenseTokenLimitHook_beforeRegisterDerivative_incrementTotalLicenseTokenSupply()
Purpose: Validates that the beforeRegisterDerivative() hook correctly increments the total license token supply when a new derivative is registered.
Before:
After:
=> fix(test): add test case to total license token limit hook

test/SPGNFT.t.sol, test/workflows/RoyaltyTokenDistributionWorkflows.t.sol
This PR adds two test cases for the SPGNFT contract:
- testFuzz_SPGNFT_mint: fuzzing test ensuring the mint() function works correctly for different nftMetadataURI and nftMetadataHash parameters
- test_SPGNFT_mintByPeriphery_revert_callerNotPeriphery: ensures the mintByPeriphery function reverts if called by an address that is not a periphery address
=> Add  fuzzing and unit tests for mint and mintByPeriphery functions in SPGNFT

contracts/SPGNFT.sol, contracts/interfaces/ISPGNFT.sol, contracts/lib/Errors.sol, test/SPGNFT.t.sol, test/workflows/RoyaltyTokenDistributionWorkflows.t.sol
This PR adds functionality to allow NFT owners to update the metadata (both URI and hash) of their tokens in SPGNFT collections. It fixes this issue: https://github.com/storyprotocol/protocol-periphery-v1/issues/232
- Added `setTokenURI(uint256 tokenId, string memory tokenUri, bytes32 nftMetadataHash) `external function in SPGNFT.sol -> allows token owners to update both metadata URI and metadata hash for their tokens
- Validates caller is the token owner using ownerOf() check
- Calls _setTokenURI() to update the token's URI
- Updates the nftMetadataHashToTokenId mapping
- Added `setTokenURI(uint256 tokenId, string memory tokenUri, bytes32 nftMetadataHash)` function declaration in ISPGNFT.sol
- Marked the existing `setTokenURI(uint256 tokenId, string memory tokenUri)` function as …
=> Fix: SPGNFT metadata hash setter
